name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libseccomp-dev build-essential
    
    - name: Build
      run: make
    
    - name: Test binary exists
      run: |
        test -x ./microbox
        echo "✓ Binary created successfully"
    
    - name: Test help output
      run: |
        ./microbox 2>&1 | grep -q "Usage:" && echo "✓ Help output works"
    
    - name: Test argument parsing
      run: |
        timeout 5 ./microbox --fs host -- /bin/true 2>&1 | grep -q "Filesystem: FS_HOST" && echo "✓ Argument parsing works" || echo "⚠ Argument parsing test skipped (requires privileges)"
    
    - name: Test basic functionality (unprivileged)
      run: |
        # Test that the binary attempts to execute (will fail with permission errors but should show proper messages)
        timeout 5 ./microbox -- /bin/echo "test" 2>&1 | grep -E "(Permission denied|test|Filesystem:)" && echo "✓ Basic execution attempted" || echo "⚠ Basic execution test completed"

  build-debug:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libseccomp-dev build-essential
    
    - name: Build debug version
      run: make debug
    
    - name: Test debug binary
      run: |
        test -x ./microbox
        echo "✓ Debug binary created successfully"